"""Add books and subscriptions tables

Revision ID: 1f34778aff5b
Revises: 7bbe8fe6258c
Create Date: 2025-12-24 12:54:53.176788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f34778aff5b'
down_revision = '7bbe8fe6258c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###