"""add_user_roles_and_author_user_relationship

Revision ID: 68e6358a3841
Revises: 1f34778aff5b
Create Date: 2025-12-24 15:03:06.594597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e6358a3841'
down_revision = '1f34778aff5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First create the enum type
    op.execute("CREATE TYPE userrole AS ENUM ('USER', 'AUTHOR')")
    
    # Add the role column to users with a default value
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'AUTHOR', name='userrole'), nullable=False, server_default='USER'))
    
    # Add user_id column to authors as nullable first
    op.add_column('authors', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Create a temporary user for existing authors
    connection = op.get_bind()
    
    # Get existing authors
    result = connection.execute(sa.text("SELECT id, name FROM authors"))
    authors = result.fetchall()
    
    for author in authors:
        # Create a user for each existing author
        user_result = connection.execute(
            sa.text("INSERT INTO users (email, username, hashed_password, role) VALUES (:email, :username, :password, 'AUTHOR') RETURNING id"),
            {
                'email': f"{author.name.lower().replace(' ', '.')}@author.com",
                'username': author.name,
                'password': 'temp_password_hash'  # This should be changed
            }
        )
        user_id = user_result.fetchone()[0]
        
        # Update the author with the new user_id
        connection.execute(
            sa.text("UPDATE authors SET user_id = :user_id WHERE id = :author_id"),
            {'user_id': user_id, 'author_id': author.id}
        )
    
    # Now make user_id not nullable
    op.alter_column('authors', 'user_id', nullable=False)
    op.create_unique_constraint(None, 'authors', ['user_id'])
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_column('authors', 'user_id')
    op.drop_column('users', 'role')
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###